version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - DATABASE_URL=sqlite:///task_manager.db
      - SECRET_KEY=sua_chave_secreta
    volumes:
      - .:/app
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
volumes:
  grafana-storage:
