name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'  # Ajustado para a versão correta usada no projeto

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libdbus-1-dev

    - name: Install Python dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        source venv/bin/activate
        pip install coverage
        # Descobre e executa os testes
        coverage run --source=. -m unittest discover -s tests -p 'test_*.py'
        coverage report
        coverage html -d coverage_html_report

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage_html_report

    - name: Bandit Security Scan
      run: |
        source venv/bin/activate
        pip install bandit
        # Usa o arquivo de configuração personalizado do Bandit
        bandit -r . -c bandit.yaml

    - name: OWASP Dependency-Check
      run: |
        sudo apt-get update
        # Instala o OWASP Dependency Check usando o método certo
        curl -L https://github.com/jeremylong/DependencyCheck/releases/download/v6.5.3/dependency-check-6.5.3-release.zip -o dependency-check.zip
        unzip dependency-check.zip -d dependency-check
        ./dependency-check/bin/dependency-check.sh --scan ./ --format "HTML" --out report.html

    - name: Upload dependency-check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: report.html
