name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        source venv/bin/activate
        pip install coverage
        coverage run -m unittest discover
        coverage report
        coverage html -d coverage_html_report

    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage_html_report

    - name: Bandit Security Scan
      run: |
        source venv/bin/activate
        pip install bandit
        bandit -r .

    - name: OWASP Dependency-Check
      run: |
        sudo apt-get update
        sudo apt-get install -y owasp-dependency-check
        dependency-check --scan ./ --format "HTML" --out report.html

    - name: Upload dependency-check report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-report
        path: report.html
