name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "source $(pwd)/venv/bin/activate" >> $GITHUB_ENV

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel meson ninja-build libdbus-1-dev

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Meson build
      run: |
        source venv/bin/activate
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
        meson setup build
        ninja -C build

    - name: Run Tests
      run: |
        source venv/bin/activate
        pip install coverage
        coverage run -m unittest discover
        coverage report
        coverage html -d coverage_html_report

    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage_html_report

    - name: Bandit Security Scan
      run: |
        source venv/bin/activate
        pip install bandit
        bandit -r .

    - name: OWASP Dependency-Check
      run: |
        sudo apt-get update
        sudo apt-get install -y owasp-dependency-check
        dependency-check --scan ./ --format "HTML" --out dependency-check-report.html

    - name: Upload dependency-check report
      uses: actions/upload-artifact@v3
      with:
        name: dependency-check-report
        path: dependency-check-report.html
