name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Atualizado para a vers達o v4

    - name: Set up Python
      uses: actions/setup-python@v4  # Atualizado para a vers達o v4
      with:
        python-version: '3.8'

    - name: Create and activate virtual environment
      run: |
        python -m venv venv
        echo "VIRTUAL_ENV=$(pwd)/venv" >> $GITHUB_ENV
        echo "PATH=$(pwd)/venv/bin:$PATH" >> $GITHUB_ENV

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel meson ninja-build libdbus-1-dev

    - name: Install Python dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Meson build
      run: |
        source venv/bin/activate
        export PKG_CONFIG_PATH=/usr/lib/x86_64-linux-gnu/pkgconfig
        meson setup build
        ninja -C build

    - name: Run Tests with Coverage
      run: |
        source venv/bin/activate
        pip install coverage
        coverage run --source=app -m unittest discover -s tests
        coverage report
        coverage html -d coverage_html_report

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4  # Atualizado para a vers達o v4
      with:
        name: coverage-report
        path: coverage_html_report

    - name: Bandit Security Scan
      run: |
        source venv/bin/activate
        pip install bandit
        bandit -r app

    - name: Install OWASP Dependency-Check
      run: |
        wget https://github.com/jeremylong/DependencyCheck/releases/download/v8.4.0/dependency-check-8.4.0-release.zip -O dependency-check.zip
        unzip dependency-check.zip -d dependency-check
        export PATH=$PATH:$(pwd)/dependency-check/bin

    - name: OWASP Dependency-Check Scan
      run: |
        dependency-check/bin/dependency-check.sh --purge --scan ./ --format "HTML" --out dependency-check-report.html  # Comando atualizado com a flag --purge

    - name: Upload Dependency-Check Report
      uses: actions/upload-artifact@v4  # Atualizado para a vers達o v4
      with:
        name: dependency-check-report
        path: dependency-check-report.html
